### ISSUE TITLE
Doesn't work in rails 4.2.7.1 with ruby 2.3.1p112

### ISSUE THREAD

**Issue by sgrosse** [reed/actionview-encoded_mail_to#15]
In my rails app it works from console but not within any *.html.haml or *.html.erb views. I moved the `_mail_to_with_encoding` method to my application helper. After some debugging I found out that in my case: `encode = html_options.delete("encode").to_s` from 
https://github.com/reed/actionview-encoded_mail_to/blob/master/lib/action_view/encoded_mail_to/mail_to_with_encoding.rb#L62 simply returns an empty string. I changed it to `encode = html_options.delete(:encode).to_s` and everything works fine.

But ...

Changing this in my fork of the actionview-encoded_mail_to-gem turned out, that the mail_to method from the gem isn't used at all. I have no idea why.

And of course it wouldn't be a proper fix since the tests are failing.

**Comment by apurvis** [comment]
seeing the same issue

**Comment by reed** [comment]
@sgrosse There's nothing wrong with that line of code.  You're not meant to call `_mail_to_with_encoding` directly.  It's called by `mail_to`, which converts all the keys to strings first.  

@tricknotes It would appear that the changes you made (switching from `alias_method_chain` to `module#prepend`) have rendered this gem useless.  Do you have any ideas?  I've found that prepending our module to `ActionView::RoutingUrlFor` instead of `ActionView::Helpers::UrlHelper` resolves the issue, but I have no idea why.

**Comment by tuesy** [comment]
FYI Also seeing this in Rails 5.0.0.1 and 1.0.8

**Comment by echarp** [comment]
I think I found a way to use this gem.

In `config/application.rb`, just after the first `require 'rails/all'` line, add the following line:
`require 'action_view/encoded_mail_to/mail_to_with_encoding'`

That way your haml will actually encode email addresses.

**Comment by paulewetzel** [comment]
I am having the same kind of issues with Rails 4.2.0.

**Comment by paulewetzel** [comment]
@reed Regarding " There's nothing wrong with that line of code". This is what I get when I run the following code in irb

html_options = {"encoding": "javascript"} 
encode = html_options.delete("encode").to_s
encode == ""
so the  
case encode
          when "javascript" 

will never execute.

**Comment by reed** [comment]
@paulewetzel You ignored what I said after I said there's nothing wrong with the code.  The method is a private method only called by `mail_to`, which explicitly converts the keys to strings before passing the options to the private method.  Therefore, the key will **never** be a symbol.  It will **always** be a string.  So attempting to delete a symbol instead of a string would actually create the problem you're trying to fix.

**Comment by paulewetzel** [comment]
Yes, I noticed the .stringify_keys! method after I ran some print lines and determined it was working. I had deleted my comment, but I guess not in time. 

BTW, when I add a require 'action_view/encoded_mail_to/mail_to_with_encoding' to the config/application.rb, I end up getting both the standard link and the encoded script, one right after the other. If I take that out the require statement, the mail_to method only returns a standard mailto link, regardless of the options passed in.

**Comment by echarp** [comment]
I think found another "cleaner" way to use this nice gem.

In `Gemfile`, include the gem using the following line:
`gem 'actionview-encoded_mail_to',
    require: 'action_view/encoded_mail_to/mail_to_with_encoding'`

This `require` element is necessary in my project => http://www.agendadulibre.org

**Comment by paulewetzel** [comment]
Hi all, I am trying to figure out exactly how this gem is suppose to work. I forked the gem, changed the last line of the MailToWithEncoding module to prepend to ApplicationHelper,
ApplicationHelper.send :prepend, ActionView::EncodedMailTo::MailToWithEncoding, instead of 
ActionView::Helpers::UrlHelper, which fixes the requirement issue. 

Next, I created this link <%= mail_to "test@test.com" ,"Joe Test" , encode: "javascript"  %>  
 in my app and traced some values within _mail_to_with_encoding method was executed. Here is what I got back:

1. email_address_obfuscated test@test.com
2. email_address_obfuscated test@test.com
3. email_address_obfuscated test@test.com
4. set_attributes  a.setAttribute('href', 'mailto:test@test.com');
5. link_content = a.appendChild(document.createTextNode('Joe Test'));
6. creat_link= var script = document.getElementById('mail_to-f9ooviyn');var a = document.createElement('a');a.setAttribute('href', 'mailto:test@test.com');a.appendChild(document.createTextNode('Joe Test'));script.parentNode.insertBefore(a,script);
7. string = %76%61%72%20%73%63%72%69%70%74%20%3d%20%64%6f%63%75%6d%65%6e%74%2e%67%65%74%45%6c%65%6d%65%6e%74%42%79%49%64%28%27%6d%61%69%6c%5f%74%6f%2d%66%39%6f%6f%76%69%79%6e%27%29%3b%76%61%72%20%61%20%3d%20%64%6f%63%75%6d%65%6e%74%2e%63%72%65%61%74%65%45%6c%65%6d%65%6e%74%28%27%61%27%29%3b%61%2e%73%65%74%41%74%74%72%69%62%75%74%65%28%27%68%72%65%66%27%2c%20%27%6d%61%69%6c%74%6f%3a%74%65%73%74%40%74%65%73%74%2e%63%6f%6d%27%29%3b%61%2e%61%70%70%65%6e%64%43%68%69%6c%64%28%64%6f%63%75%6d%65%6e%74%2e%63%72%65%61%74%65%54%65%78%74%4e%6f%64%65%28%27%4a%6f%65%20%54%65%73%74%27%29%29%3b%73%63%72%69%70%74%2e%70%61%72%65%6e%74%4e%6f%64%65%2e%69%6e%73%65%72%74%42%65%66%6f%72%65%28%61%2c%73%63%72%69%70%74%29%3b

I am guessing that at 4. a.setAttribute('href', 'mailto:test@test.com'), the mailto value should not be the clear text email address.  Am I correct in assuming that?

**Comment by paulewetzel** [comment]
@reed Are you going change the prepend target within the next few days, or should I just use my fork?

**Comment by reed** [comment]
Just released v1.0.9 which should restore functionality to this gem.  Let me know if it's not working for you.

**Comment by paulewetzel** [comment]
Awesome, thanks for getting that out quickly!

**Comment by paulewetzel** [comment]
Yes, seems to be working for me.
